spring:
  datasource:
    url: jdbc:mysql://localhost:3307/jpa?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#jpa配置
  jpa:
    hibernate:
      #更新或者创建数据表结构
      ddl-auto: update
      #控制台显示sql
    show-sql: true